language: c

script: asdf plugin-test glooctl https://github.com/virtualstaticvoid/asdf-glooctl.git

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

os:
  - linux
